# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      # Install Solana
      - run: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      - run: export PATH="~/.local/share/solana/install/active_release/bin:$PATH"
      - run: ls -laR ~/.local/share/solana/install/active_release/bin
      - run: ~/.local/share/solana/install/active_release/bin/solana-test-validator &
      # Run tests
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run integration-test
