# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      TWITTER_API_KEY_BEARER_TOKEN: ${{ secrets.TWITTER_API_KEY_BEARER_TOKEN }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      # Metaplex program location is not a secret so don't
      # worry about including it in this file
      METAPLEX_TOKEN_METADATA_PROGRAM_ADDRESS: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Solana
      - run: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      - run: export PATH="~/.local/share/solana/install/active_release/bin:$PATH"
      # Run Solana validator with Metaplex program
      - run: ~/.local/share/solana/install/active_release/bin/solana-test-validator --bpf-program ${METAPLEX_TOKEN_METADATA_PROGRAM_ADDRESS} metaplex_token_metadata_program.so --reset &
      # Run tests
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
