# From https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs#using-the-nodejs-starter-workflow
name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    env:
      TWITTER_API_KEY_BEARER_TOKEN: ${{ secrets.TWITTER_API_KEY_BEARER_TOKEN }}
      IDENTITY_TOKEN_SECRET_KEY: ${{ secrets.IDENTITY_TOKEN_SECRET_KEY }}
      MIKES_MNEMONIC: ${{ secrets.MIKES_MNEMONIC }}
      MIKES_SECRET_KEY: ${{ secrets.MIKES_SECRET_KEY }}
      # Program locations are not a secret so don't
      # worry about including them in this file
      METAPLEX_TOKEN_METADATA_PROGRAM_ADDRESS: "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
      MEMO_PROGRAM_ADDRESS: "MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"
      # We skip certain network-using tests on GitHub
      ON_GITHUB: "true"

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Solana
      - run: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
      - run: export PATH="~/.local/share/solana/install/active_release/bin:$PATH"
      # Run Solana validator with Metaplex program
      - run: ~/.local/share/solana/install/active_release/bin/solana-test-validator --bpf-program ${METAPLEX_TOKEN_METADATA_PROGRAM_ADDRESS} on-chain-programs/metaplex_token_metadata_program.so --reset &
      # Run CORS proxy (needed to access Decaf receipts)
      # For some reason 'npx' fails with "could not determine executable to run"
      - run: ./node_modules/.bin/lcp --proxyUrl https://www.decaf.so
      # Run tests
      - run: npm ci
      - run: npm run build:extension --if-present
      - run: npm test
